### ISSUE TITLE
validate_fasta.py duplicates the sequence if there is no header line

### ISSUE THREAD

**Issue by cat-bro** [usegalaxy-au/tools-au#22]
This came up in azure testing:  If the amino acid sequence does not have a header line, the sequence is concatenated with itself before the characters are counted. A 1999aa sequence is measured to be a 3998aa sequence and rejected for being over the maximum allowed length.

This is not prohibitive to the testing since we can get around it by using a header line.

**Comment by neoformit** [comment]
Resolved by a6224348958d9f6383e54b57e4fd16ef27471b2a pending testing
