### ISSUE TITLE
Latest alphafold was uninstalled from Galaxy Australia

### ISSUE THREAD

**Issue by cat-bro** [usegalaxy-au/tools-au#83]
The latest alphafold wrapper does not work with pulsar. It must have something to do with the validate_fasta.py script having been moved into a subdirectory. From the error, it looks like the script is no longer copied to pulsar. The error is:

```
python3: can't open file '/mnt/pulsar/files/staging/6253967/tool_files/scripts/validate_fasta.py': [Errno 2] No such file or directory
```

The script can be included using <required_files>...</required_files> in the tool wrapper. There are some tools that use this including maxquant.

**Comment by neoformit** [comment]
Resolved with https://github.com/usegalaxy-au/tools-au/commit/6cd8c5dd3af93aeb916c795b7692a5427e57eff3
